name: build-docs
run-name: ${{ github.actor }} is building docs
on: [push]
jobs:
    build-tutorial:
        runs-on: ubuntu-latest
        container:
            image: texlive/texlive:TL2021-historic
        steps:
            - uses: actions/checkout@v3

            - name: install-pandoc
              run: apt-get update && apt-get install -y bash git pandoc

            - name: build
              run: ./build-docs.sh

            - uses: actions/upload-artifact@v3
              with:
                  name: output
                  path: docs/
